name: packing_defect-docs
channels:

  - conda-forge

dependencies:
    # Base depends
  - python
  - pip
  - sphinx

  - sphinx_rtd_theme

  - mdanalysis-sphinx-theme >=1.0.1
    # Pip-only installs
  #- pip:
